#!/bin/bash

set -e

cd "$(dirname "$0")/.."

if [ ! -f .tool-versions ]; then
    echo "? Error: .tool-versions file not found!" >&2
    exit 1
fi

ELIXIR_VERSION=$(awk '/^elixir / {print $2}' .tool-versions)

if [ -z "$ELIXIR_VERSION" ]; then
    echo "? Error: Elixir version not found in .tool-versions!" >&2
    exit 1
fi

DOCKER_IMAGE="elixir:${ELIXIR_VERSION}-alpine"

echo "$DOCKER_IMAGE"
