#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.
# https://github.com/github/scripts-to-rule-them-all

set -e

cd "$(dirname "$0")/.."

MIX_ENV=test script/update

echo "==> Disallow compile warnings..."

mix compile --warnings-as-errors

echo "==> Check formatted..."

mix format --check-formatted

echo "==> Check unused deps in mix.lock..."

mix deps.unlock --check-unused

echo "==> Running credo..."

mix credo suggest --min-priority high

echo "==> Running dialyzer..."

mix dialyzer

echo "==> Running tests..."

# MIX_ENV=test mix propcheck.clean
# Umbrella apps have multiple test suites, so failed tests are unobtrusive.
# To make obvious that tests failed, we run failed tests separately.
mix test || true
mix test --failed
